name: shipping_cart
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  hexcolor: ^3.0.1
  otp_text_field: ^1.1.3
  font_awesome_flutter: ^10.5.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  get: ^4.6.5
  fancy_bottom_navigation: ^0.3.3
  go_router: ^9.0.3
  flutter_sliding_up_panel: ^2.0.1
  sliding_up_panel2: ^3.3.0+1
  sliding_up_panel: ^2.0.0+1
  email_otp: ^2.0.1
  intl: ^0.18.1
  flutter_paypal: ^0.0.8
  webview_flutter_x5: ^2.0.8+9
  flutter_paypal_checkout: ^1.0.1
  http_auth: ^1.0.2
  http: ^0.13.6
  webview_flutter: ^2.1.1
  getwidget: ^3.1.1
  firebase_storage: ^11.2.5
  auto_size_text: ^3.0.0
  email_auth: ^1.0.0
  flutter_dotenv: ^5.1.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  flutter_email_sender: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - lib/.env

  